name: Build VOL IUWEB FE
description: Build VOL IUWEB FE

runs:
  using: 'composite'
  steps:

    - name: Download the compose file
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        php -r "unlink('composer-setup.php');"
      shell: bash

    - name: Install Composer dependencies
      run: |
       composer install --optimize-autoloader --no-interaction --no-dev
      shell: bash

    - name: Build VOL IUWEB FE
      run: |
        date > config/version
        git describe --all >> config/version
        tar cvzf selfserve.tar.gz --exclude=config/autoload/local.php \
          --exclude=config/autoload/local.php.dist composer.lock init_autoloader.php config module public data/autoload data/cache vendor
      shell: bash
