<ol class="breadcrumbs">
  <?php use Olcs\Logging\Log\Logger;
  Logger::crit(print_r("Pages: ".count($this->pages), true));
  foreach ($this->pages as $key => $page):
      Logger::crit(print_r($page->getLabel(), true));
      ?>
  <?php if ($key < count($this->pages) - 1): ?>
  <li class="breadcrumbs__item"><a href="<?php echo $page->getHref(); ?>"><?php echo $this->translate($page->getLabel()); ?></a></li>
  <?php else: ?>
  <li class="breadcrumbs__item current"><?php echo $this->translate($page->getLabel()); ?></li>
  <?php endif; ?>
  <?php endforeach; ?>
</ol>
