name: CI

on:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  security:
    uses: dvsa/.github/.github/workflows/php-security.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  psalm:

    name: Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          extensions: mbstring, intl, redis-phpredis/phpredis
          tools: vimeo/psalm, composer:v2
        env:
          REDIS_CONFIGURE_OPTS: --enable-redis-igbinary

      - name: Install Composer dependancies
        run: composer install --no-progress --no-interaction

      - name: Execute Psalm
        run: psalm --no-progress --output-format=github --root=${GITHUB_WORKSPACE}

  tests:
    uses: dvsa/.github/.github/workflows/php-tests.yml@main
    with:
      php-versions: "[\"8.2\"]"
      fail-fast: false
