<?php

namespace Olcs\Controller\Messages;

use Laminas\View\Model\ViewModel;
use Olcs\Controller\AbstractInternalController;
use Olcs\Controller\Interfaces\LeftViewProvider;
use Olcs\Controller\Interfaces\LicenceControllerInterface;
use Dvsa\Olcs\Transfer\Query\Messaging\GetConversationList;
use Dvsa\Olcs\Transfer\Query\IrhpApplication\InternalApplicationsSummary;
use Common\Controller\Interfaces\ToggleAwareInterface;
use Common\FeatureToggle;
use Olcs\Controller\Interfaces\RightViewProvider;
use Olcs\Listener\RouteParam\Licence;

class LicenceConversationListController extends AbstractInternalController implements LeftViewProvider, LicenceControllerInterface, ToggleAwareInterface
{

    protected $navigationId = 'conversations';
    protected $listVars = ['licence'];
    //protected $defaultTableLimit = 10;
    protected $listDto =  GetConversationList::class; //InternalApplicationsSummary::class;
    protected $routeIdentifier = 'messages';
    protected $tableName = 'conversations-list'; //Olcs/src/Table/Tables/task-history (table.php)
    protected $tableViewTemplate = 'pages/table';
    protected $toggleConfig = [
        'default' => [
            FeatureToggle::MESSAGING
        ],
    ];


    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

    /**
     * Get left view
     *
     * @return ViewModel
     */
    public function getLeftView()
    {
        $view = new ViewModel();
        $view->setTemplate('sections/messages/partials/left');

        return $view;
    }

    /**
     * Get right view
     *
     * @return ViewModel
     */
    public function getRightView()
    {
//        $licenceId = (int) $this->params()->fromRoute('licence', null);
//        $this->placeholder()->setPlaceholder('licence',$licenceId);
        $view = new ViewModel();
        $view->setTemplate('sections/messages/partials/right');

        return $view;
    }
}